### ISSUE TITLE
No recommendations on staying safe with images and removal of EXIF data?

### ISSUE THREAD

**Issue by chsados** [prism-break/prism-break#2044]
Looking for a FOSS or approved program to strip all EXIF data or scrambler.  Are there any future plans to include this or any suggestions one can point to here?

**Comment by alerque** [comment]
Stripping EXIF info is not a network operation and hence not really relevant to PRISM-Break. Also this is the wrong issue tracker if it was. Also "staying safe" while posting images of anything (EXIF or no EXIF) is not really a thing and would be more complicated than the communication security we cover (because it's less mathematical and more OpSec).
